RateMyLecturer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^log/', include('log.urls', namespace='log')),
    url(r'^lecturer/', include('lecturer.urls', namespace='lecturer')),
]

lecturer/urls.py
from django.conf.urls import url
from . import views
from . import requests

urlpatterns = [
    url(r'^$', views.searchForLecturer, name='searchForLecturer'),
    url(r'^search$', views.searchForLecturer, name='searchForLecturer'),
    url(r'^add$', views.addLecturer, name='add'),
    url(r'^(?P<lecturer_id>[0-9]+)/$', views.lecturerPage, name='lecturerPage'),
    url(r'^universityPage/(?P<university_id>[0-9]+)/$', views.universityPage, name='universityPage'),

    # requests
    url(r'^requests/searchUniversities$', requests.searchUniversities, name='searchUniversities'),
    url(r'^requests/searchDepartments$', requests.searchDepartments, name='searchDepartments'),
    url(r'^requests/searchLecturers$', requests.searchLecturers, name='searchLecturers'),
    url(r'^requests/rateLecturer$', requests.rateLecturer, name='rateLecturer'),
    url(r'^requests/getRatingForLecturer$', requests.getRatingForLecturer, name='getRatingForLecturer'),
    url(r'^requests/getAverageRating$', requests.getAverageRating, name='getAverageRating'),
    url(r'^requests/addComment$', requests.addComment, name='addComment'),
    url(r'^requests/getComments$', requests.getComments, name='getComments'),
    url(r'^requests/deleteComment$', requests.deleteComment, name='deleteComment'),
    url(r'^requests/changeScoreForComment$', requests.changeScoreForComment, name='changeScoreForComment'),
    url(r'^requests/getDomainForUniversityName$', requests.getDomainForUniversityName, name='getDomainForUniversityName'),

]

log/urls.py
from django.conf.urls import url
from . import views
from . import requests

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),

    # requests
    url(r'^requests/checkUsernameExists$', requests.checkUsernameExists, name='requests_checkUsernameExists'),
]

main/urls.py
from django.conf.urls import url
from . import views, requests

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # REQUESTS
    url(r'^requests/getAllUniversitiesAsOptions$', requests.getAllUniversitiesAsOptions, name='getAllUniversitiesAsOptions'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from lecturer.models import Lecturer, University

def index(request):
    lecturers = reversed(sorted(Lecturer.objects.all(), key=lambda r: r.get_rating())[-5:])
    universities = reversed(sorted(University.objects.all(), key=lambda r: r.get_rating())[-5:])

    return render(request, 'main/index.html', {'lecturers': lecturers, 'universities': universities})

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head lang="en">
        <meta charset="utf-8"/>
        <title>
            {% block title_block %}
                Rate My Lecturer
            {% endblock %}
        </title>
        
		<link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'>
        <link rel="stylesheet" href="/static/Bootstrap/css/custom.css">
        <link type='text/css' href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        
        <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/AjaxQueue.js' %}"></script>

        <script type="text/javascript" src="{% static 'js/SearchLecturersScript.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/UniversitySelectScript.js' %}"></script>

        {% block script_block %}
        {% endblock %}
    </head>
    <body>
    <div class="site-wrapper">
		<div class="container inner">
              <a href="{% url 'main:index' %}"><img src="/static/img/logo.png" class="masthead-brand" height=27% width=27%></a>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="{% url 'main:index' %}">Home</a></li>
						{% if user.is_authenticated %}
							 <li class="active"><a href="{% url 'lecturer:add' %}">Add Lecturer</a></li>
                             <li class="active"><a href="{% url 'log:logout' %}">Log Out </a></li>
							
						{% else %}
							<li class="active"><a href="{% url 'log:signup' %}">Sign Up </a></li>
							<li class="active"><a href="{% url 'log:login' %}">Log In</a></li>
						{% endif %}
                    <form class="navbar-form navbar-right" role="search">
						<div class="form-group">
                            <select class="form-control" id="universitiesSelect" onchange="universitiesSelectChanged()">
                            </select>
							<input type="text" class="form-control" id="lecturer"
								onkeyup="searchLecturers()" placeholder="Lecturer Search">
						</div>
					</form>
                  </ul>
                </nav>        
            </div>
      <div class="container inner">
		
        <div class="container">
          <div class="masthead clearfix">
            
            <div class="well" id="lecturerResults" style="display:none"> </div>
            {% block body_block %}
				This is body_block's default content.
            {% endblock %}    
          </div>    
          </div>
        </div>
        </div>
        
    </body>
    
    
    
    
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title_block %}
    Welcome to Rate My Lecturer
{% endblock %}

{% block body_block %}

    {% if user.is_authenticated %}
 <h2 class="text-center"><font color=#0077b0>Hello</font> {{ user.username }}, <font color=#0077b0> Welcome to Rate my Lecturer.</font></h2> <br>
	{% else %}
<font color=#0077b0><h2 class="text-center">Welcome to Rate my Lecturer.</h2></font> <br>
    {% endif %}

	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<div class="well">
                <font color=#0077b0><h4 class="text-center"> Top 5 Lecturers:</h4></font>
				<table class="table table-hover">
                    {% for lecturer in lecturers %}
                    <tr>
						<td class="text-left"><a id="link" href="/lecturer/{{lecturer.id}}">{{lecturer.title}} {{lecturer.first_name}} {{lecturer.last_name}}</a></td>
						<td class="text-right"> {{lecturer.get_rating}} </td>
					</tr>
                    {% endfor %}
				</table>
			</div>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<div class="well">
                <font color=#0077b0><h4 class="text-center"> Top 5 Universities: </h4></font>
				<table class="table table-hover">
                    {% for university in universities %}
					<tr>
						<td class="text-left"><a id="link" href="/lecturer/universityPage/{{university.id}}">{{university.name}}</a></td>
						<td class="text-right"> {{university.get_rating}} </td>
					</tr>
                    {% endfor %}
				</table>
			</div>
		</div>
	</div>


{% endblock %}

main/templates/main/index2.html
{% extends 'main/base.html' %}

{% block title_block %}
    Welcome to Rate My Lecturer
{% endblock %}

{% block body_block %}

    {% if user.is_authenticated %}
		<h2 class="text-center">Hello {{ user.username }}, Welcome to Rate My Lecturer</h2> <br>
	{% else %}
		<h2 class="text-center">Welcome to Rate My Lecturer</h2> <br>
    {% endif %}

	<div class="row">
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<div class="well">
				<h4 class="text-center"> Top 5 Lecturers </h4>
				<table class="table table-hover">
                    {% for lecturer in lecturers %}
                    <tr>
						<td class="text-center"><a id="link" href="/lecturer/{{lecturer.id}}">{{lecturer.title}} {{lecturer.first_name}} {{lecturer.last_name}}</a></td>
						<td class="text-left"> {{lecturer.get_rating}} </td>
					</tr>
                    {% endfor %}
				</table>
			</div>
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<div class="well">
				<h4 class="text-center"> Top 5 Universities </h4>
				<table class="table table-hover">
                    {% for university in universities %}
					<tr>
						<td class="text-center"><a id="link" href="/lecturer/universityPage/{{university.id}}">{{university.name}}</a></td>
						<td class="text-left"> {{university.get_rating}} </td>
					</tr>
                    {% endfor %}
				</table>
			</div>
		</div>
	</div>


{% endblock %}

main/templates/main/indexstyle.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Bootstrap Cover Template</title>
  
  
  <link rel='stylesheet prefetch' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css'>

      <link rel="stylesheet" href="/static/Bootstrap/css/custom.css">

  
</head>

<body>
  
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="container">

          <div class="masthead cl earfix">
            <div class="container inner">
              <h3 class="masthead-brand">Cover</h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">Features</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">Cover your page.</h1>
            <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
            <p class="lead">
              <a href="#" class="btn btn-lg btn-default">Learn more</a>
            </p>
          </div>

        </div>

      </div>

    </div>
  
  
</body>
</html>